name: Run black linter
on:
  pull_request:
    types: [opened, synchronize, reopened, synchronize]
    branches:
      - main
    paths:
      - "**/*.py"
permissions:
  contents: read
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
